"""init

Revision ID: 184091932753
Revises: 
Create Date: 2026-03-12 15:37:21.773367+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184091932753'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['prompt_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_runs_prompt_id', 'prompt_runs', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_runs_version_id', 'prompt_runs', ['version_id'], unique=False)
    op.add_column('environments', sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint(op.f('environments_name_key'), 'environments', type_='unique')
    op.create_index('ix_environments_project_id', 'environments', ['project_id'], unique=False)
    op.create_unique_constraint('uq_environment_project_name', 'environments', ['project_id', 'name'])
    op.drop_constraint(op.f('environments_project_id_fkey'), 'environments', type_='foreignkey')
    op.create_foreign_key(None, 'environments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('environments', 'isDefault')
    op.drop_constraint(op.f('projects_name_key'), 'projects', type_='unique')
    op.create_index('ix_projects_team_id', 'projects', ['team_id'], unique=False)
    op.create_unique_constraint('uq_project_team_name', 'projects', ['team_id', 'name'])
    op.drop_constraint(op.f('projects_team_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.add_column('prompt_environments', sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.drop_constraint(op.f('prompt_environments_version_key'), 'prompt_environments', type_='unique')
    op.create_index('ix_prompt_environments_environment_id', 'prompt_environments', ['environment_id'], unique=False)
    op.create_foreign_key(None, 'prompt_environments', 'prompt_versions', ['version_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('prompt_environments', 'version')
    op.drop_constraint(op.f('prompt_versions_version_key'), 'prompt_versions', type_='unique')
    op.create_index('ix_prompt_versions_prompt_id', 'prompt_versions', ['prompt_id'], unique=False)
    op.add_column('prompts', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('prompts', sa.Column('head_version_id', sa.Integer(), nullable=True))
    op.create_index('ix_prompts_project_id', 'prompts', ['project_id'], unique=False)
    op.drop_constraint(op.f('prompts_project_id_fkey'), 'prompts', type_='foreignkey')
    op.create_foreign_key(None, 'prompts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prompts', 'prompt_versions', ['head_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('prompts', 'head_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('head_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.create_foreign_key(op.f('prompts_project_id_fkey'), 'prompts', 'projects', ['project_id'], ['id'])
    op.drop_index('ix_prompts_project_id', table_name='prompts')
    op.drop_column('prompts', 'head_version_id')
    op.drop_column('prompts', 'is_active')
    op.drop_index('ix_prompt_versions_prompt_id', table_name='prompt_versions')
    op.create_unique_constraint(op.f('prompt_versions_version_key'), 'prompt_versions', ['version'], postgresql_nulls_not_distinct=False)
    op.add_column('prompt_environments', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prompt_environments', type_='foreignkey')
    op.drop_index('ix_prompt_environments_environment_id', table_name='prompt_environments')
    op.create_unique_constraint(op.f('prompt_environments_version_key'), 'prompt_environments', ['version'], postgresql_nulls_not_distinct=False)
    op.drop_column('prompt_environments', 'version_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_team_id_fkey'), 'projects', 'teams', ['team_id'], ['id'])
    op.drop_constraint('uq_project_team_name', 'projects', type_='unique')
    op.drop_index('ix_projects_team_id', table_name='projects')
    op.create_unique_constraint(op.f('projects_name_key'), 'projects', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('environments', sa.Column('isDefault', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'environments', type_='foreignkey')
    op.create_foreign_key(op.f('environments_project_id_fkey'), 'environments', 'projects', ['project_id'], ['id'])
    op.drop_constraint('uq_environment_project_name', 'environments', type_='unique')
    op.drop_index('ix_environments_project_id', table_name='environments')
    op.create_unique_constraint(op.f('environments_name_key'), 'environments', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('environments', 'is_default')
    op.drop_index('ix_prompt_runs_version_id', table_name='prompt_runs')
    op.drop_index('ix_prompt_runs_prompt_id', table_name='prompt_runs')
    op.drop_table('prompt_runs')
    # ### end Alembic commands ###
